### ISSUE TITLE
Gallery 需要添加扫码功能

### ISSUE THREAD

**Issue by andycall** [openkraken/gallery#1]
Gallery 承载的是给用户提供快速体验 kraken 的工具。

对于没有客户端环境的前端工程师而言，如果他用的是个 Windows 电脑，就需要一个可以快速启动 Kraken 的 Android App 用于开发调试 Kraken 页面。

但是目前 Gallery 只能访问内置的页面，后面还需要给用户提供扫描二维码打开新页面的能力用于覆盖这部分的人群。

**Comment by wssgcg1213** [comment]
扫码功能已经由 KrakenPlaygroundApp 承载
