### ISSUE TITLE
编译成功以后安装到ipad mini5  点击demo没反应

### ISSUE THREAD

**Issue by chaim007** [openkraken/gallery#10]
Xcode build done.                                           18.3s
(lldb) Engine creation error: (error) 
--  google了一通貌似是ipad少了一个什么Taptic Engine(震动马达)
kraken依赖这个东西吗?

**Comment by andycall** [comment]
https://github.com/openkraken/kraken/blob/main/kraken/pubspec.yaml#L23
依赖了一个震动的 插件，估计是这个导致的

**Comment by wssgcg1213** [comment]
最新版本已经去除 vibrate 插件的依赖, 重新编译即可支持 iPad
