### ISSUE TITLE
gallery build & run success, but click event not work

### ISSUE THREAD

**Issue by devjiangzhou** [openkraken/gallery#12]
升级到 0.8.1 demo 可以跑起来了，但是点击事件挂了。 @andycall 麻烦看下哈

**Comment by cnryb** [comment]
遇到相同问题

**Comment by cnryb** [comment]
已经解决掉了

**Comment by cnryb** [comment]
已经解决掉了
https://github.com/openkraken/kraken/issues/611
https://github.com/openkraken/kraken/pull/612
