### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by sis-tangyuan** [openkraken/gallery#14]
Error: A value of type 'Future<bool> Function(Uri, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(Uri, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
 - 'Uri' is from 'dart:core'.
    nativeHttpClient.authenticate = f;
Error: A value of type 'Future<bool> Function(String, int, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(String, int, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
    nativeHttpClient.authenticateProxy = f;

**Comment by cnryb** [comment]
kraken 还没有对 flutter 2.5.x 进行支持，请使用 flutter 2.2.x 进行构建测试。
关于 kraken 对 flutter 2.5.x 的支持进展，请关注 https://github.com/openkraken/kraken/issues/703
