### ISSUE TITLE
求助，工程编译不通过，目前kraken 和flutter环境正常，能运行其它flutter工程。

### ISSUE THREAD

**Issue by yunxingyu** [openkraken/gallery#19]
• Flutter version 2.11.0-0.0.pre.716 at /Users/xieyutuo/Desktop/soft/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e85ba6eeae (2 hours ago), 2022-02-28 23:31:20 -0800
    • Engine revision 615a60512c
    • Dart version 2.17.0 (build 2.17.0-150.0.dev)
    • DevTools version 2.11.1

../../../.pub-cache/hosted/pub.flutter-io.cn/kraken-0.9.0/lib/widget.dart:584:44: Error: Type 'MoveSelectionRightByLineTextIntent' not found.
  void _handleMoveSelectionRightByLineText(MoveSelectionRightByLineTextIntent intent) {
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/kraken-0.9.0/lib/widget.dart:593:43: Error: Type 'MoveSelectionLeftByLineTextIntent' not found.
  void _handleMoveSelectionLeftByLineText(MoveSelectionLeftByLineTextIntent intent) {
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/kraken-0.9.0/lib/widget.dart:602:44: Error: Type 'MoveSelectionRightByWordTextIntent' not found.
  void _handleMoveSelectionRightByWordText(MoveSelectionRightByWordTextIntent intent) {
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/kraken-0.9.0/lib/widget.dart:611:43: Error: Type 'MoveSelectionLeftByWordTextIntent' not found.
  void _handleMoveSelectionLeftByWordText(MoveSelectionLeftByWordTextIntent intent) {
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/kraken-0.9.0/lib/widget.dart:620:35: Error: Type 'MoveSelectionUpTextIntent' not found.
  void _handleMoveSelectionUpText(MoveSelectionUpTextIntent intent) {
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/kraken-0.9.0/lib/widget.dart:629:37: Error: Type 'MoveSelectionDownTextIntent' not found.
  void _handleMoveSelectionDownText(MoveSelectionDownTextIntent intent) {
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/kraken-0.9.0/lib/widget.dart:638:37: Error: Type 'MoveSelectionLeftTextIntent' not found.

**Comment by andycall** [comment]
现在的 kraken 的最高 flutter 支持版本是 2.5.3
