### ISSUE TITLE
Release模式运行报错

### ISSUE THREAD

**Issue by chenzefeng09** [openkraken/gallery#2]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/chenzefeng/Development/kraken-gallery/build/app/intermediates/flutter/debug/libs.jar.
         > Transform's input file does not exist: /Users/chenzefeng/Development/kraken-gallery/build/app/intermediates/flutter/debug/libs.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleRelease failed with exit code 1

**Comment by wssgcg1213** [comment]
Please build again with latest master branch, thx.
