### ISSUE TITLE
demos/hello-vue 报错

### ISSUE THREAD

**Issue by mjlan** [openkraken/gallery#6]
![image](https://user-images.githubusercontent.com/6204215/118505668-355d1180-b75f-11eb-92a4-8e1078acca0f.png)

**Comment by wssgcg1213** [comment]
SVG 暂不支持, 可以看下你的项目里是不是用到了 svg 图片或者矢量图形

**Comment by mjlan** [comment]
我是直接clone 下来的，未做任何修改

**Comment by answershuto** [comment]
看起来是最新的 vue 版本里面加了 SVGElement 的判断，我们还没支持，我先兼容一下这个场景。
